version: '3.8'

services:
  db:
    build: .
    container_name: node_db
    ports:
      - "2001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: node12344
      POSTGRES_DB: node_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: 